scripts to calculate montg while running
nansencenter/NERSC-HYCOM-CICE pull request #178
Opened 2023-02-07 13:24 UTC by AchrefAO

2023-02-14 09:02 UTC, lilleannette requested changes
1. the updated bin/calc_montg1.py works fine - no further changes needed.
2. bin/expt_preprocess_calc_Montg.sh should be combined with the original bin/expt_preprocess.sh (with an addiotional if-statement, if needed to make it work in all cases).  The reason is that if we update other parts of bin/expt_preprocess, we do not want to have to implement the changes in two files.

2023-02-21 14:51 UTC, AlfaAli commented
@AchrefAO 
Calculating montg1 is done once, and should be part of the job that creates the nesting files. 
For example, it can be added at the end of the script "nemo_to_hycom.sh", right after the archv file is successfully created.

I think, it should not be included in expt_preprocess.sh, as this script can be run several times to copy input files to the SCRATCH dir.

2023-02-21 15:15 UTC, lilleannette commented
> @AchrefAO Calculating montg1 is done once, and should be part of the job that creates the nesting files. For example, it can be added at the end of the script "nemo_to_hycom.sh", right after the archv file is successfully created.

@AlfaAli: Because the montg1 depends on fields in the restart-file, it does need to be computed at run-time.  These fields will not change over time in a run, but for example if the model is re-initialization with a different climatology, it may change. 
> 
 I think, it should not be included in expt_preprocess.sh, as this script can be run several times to copy input files to the SCRATCH dir.

@AlfaAli An option is to include a keyword that disables the computation opf monthg1 if you are sure that it has alreasy been computed with the correct restart-file.

2023-03-07 12:21 UTC, lilleannette approved these changes

2023-03-07 12:21 UTC, merged