Updated chl profiling
nansencenter/NERSC-HYCOM-CICE pull request #181
Opened 2023-03-07 13:58 UTC by caglartac

@AlfaAli It looks like we haven't merged the new chl profiling from November last year. I am sending you a pull request. Can you double check if these changes are in line with what you are using?

2023-03-07 14:16 UTC, AlfaAli requested changes

2023-03-07 14:16 UTC, AlfaAli commented on cice/Release-5.1/source/ice_therm_shared.F90
> +         ferrmax = 9.0e-3_dbl_kind    ! max allowed energy flux error (W m-2)
@caglartac we actually don't this change. The default ferrmax=1.0e-3_dbl_kind   is fine.

2023-05-11 07:38 UTC, caglartac commented
@AlfaAli I've reverted back to  ferrmax = 1.0e-3_dbl_kind.
Is it ok to merge? Can you approve and merge it?

2023-05-11 09:44 UTC, AlfaAli approved these changes

2023-05-11 09:46 UTC, merged