Tuning CICE for reducing ice drift and increasing a bit of ice thickn…
nansencenter/NERSC-HYCOM-CICE pull request #192
Opened 2023-05-30 08:15 UTC by Jipingnersc

Tuning the parameters (dragcofficient/Pstar) in CICE for TOPAZ5 reduces sea ice drift speed and increases the sea ice thickness a little.

2023-05-31 17:44 UTC, TillRasmussen commented
What is the effect of changing the turning angle ?

2023-06-01 08:17 UTC, AlfaAli requested changes
@Jipingnersc, maybe these values should be with real of "double kind" for example
cosw = 0.9848_dbl_kind,
sinw = 0.1736_dbl_kind

2023-06-26 10:15 UTC, Jipingnersc commented
> What is the effect of changing the turning angle ?
Hunke(2010) tested the tuning angle of 20deg which clearly adjusted the SIT pattern in the Arctic with the reduced underestimation. So in our case, it may benefit to increase the ice thickness in the Euroasian basin.

Hunke, E. C. (2010), Thickness sensitivities in the CICE sea ice model,
Ocean Modell., 34, 137–149, doi:10.1016/j.ocemod.2010.05.004

2023-06-26 10:16 UTC, Jipingnersc commented on cice/Release-5.1/source/ice_dyn_shared.F90
> +         sinw = 0.1736   , & ! sin(ocean turning angle)  ! turning angle 10 deg
> 

Thanks, it can be.

2023-06-28 14:52 UTC, merged