Update nesting routines
nansencenter/NERSC-HYCOM-CICE pull request #223
Opened 2024-01-26 14:31 UTC by sgao22006

* Update nesting documentation
* Modify 'archvz2hycom_biophys.sh' in order to be able to run in parallel
* Update bio-nesting from weekly to daily
* Modify the way of writing headers in 'calc_montg1.py' and 'fix_montg1.py'

2024-01-26 16:08 UTC, AlfaAli requested changes
It looks fine  for me, but I have not test it for creating nesting files.

2024-01-26 16:08 UTC, AlfaAli commented on doc/.offlux.md.swp
You may remove these *.swp files

2024-01-26 19:55 UTC, sgao22006 commented on doc/.offlux.md.swp
They have been actually removed in this commit.

2024-01-29 10:22 UTC, AlfaAli approved these changes

2024-01-29 10:23 UTC, merged