Update the loaded modules on Betzy (2022a) to support Python version …
nansencenter/NERSC-HYCOM-CICE pull request #227
Opened 2024-03-13 13:46 UTC by Jipingnersc

Update the loading modules on Betzy to follow the compiling chain of 2022a;
The updated modules support the version 3.10 of Python;
And to add the missing sea ice mask generation script;

2024-03-14 16:58 UTC, lilleannette requested changes
Please put cice_kmt.sh in the Grid_Bathy, otherwise it looks fine.

2024-03-14 16:58 UTC, lilleannette commented on bin/cice_kmt.sh
This file should be in the folder Grid_Bathy

2024-03-15 13:53 UTC, Jipingnersc commented on bin/cice_kmt.sh
Thank you for this check. I delete the relevant files from the bin directory and further adjust the creat_ref.sh to match the location of the cice_kmt.py.

2024-03-15 14:40 UTC, lilleannette approved these changes

2024-03-15 14:41 UTC, merged